"""initial migration

Revision ID: 98e2499a8961
Revises: 
Create Date: 2024-02-13 17:50:18.550721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98e2499a8961'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alchemist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('experienceLevel', sa.Integer(), nullable=True),
    sa.Column('recipe_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alchemist'))
    )
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alchemistID', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ingredients', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('modification_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alchemistID'], ['alchemist.id'], name=op.f('fk_recipe_alchemistID_alchemist')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe')
    op.drop_table('alchemist')
    # ### end Alembic commands ###
